# Generated by Django 5.0.8 on 2024-09-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_manage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceconnectionlog',
            name='connection_method',
            field=models.CharField(default='ssh', max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceconnectionlog',
            name='connection_status',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deviceconnectionlog',
            name='hostname',
            field=models.CharField(max_length=100),
        ),
    ]
