# Generated by Django 5.0.8 on 2024-10-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_manage', '0003_alter_deviceconnectionlog_connection_status_and_more'),
        ('dcim', '0187_alter_device_vc_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceconnectionlog',
            options={'ordering': ['-connection_time']},
        ),
        migrations.AlterField(
            model_name='deviceconnectionlog',
            name='connection_method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='deviceconnectionlog',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connection_logs', to='dcim.device'),
        ),
        migrations.CreateModel(
            name='DeviceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('config_output', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='dcim.device')),
            ],
            options={
                'verbose_name': 'Конфигурация устройства',
                'verbose_name_plural': 'Конфигурации устройств',
                'ordering': ['-created_at'],
            },
        ),
    ]
