# Generated by Django 5.0.8 on 2024-10-17 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_manage', '0004_alter_deviceconnectionlog_options_and_more'),
        ('dcim', '0187_alter_device_vc_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceConfigBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('block_name', models.CharField(max_length=255)),
                ('config_block', models.TextField()),
                ('executed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_blocks', to='dcim.device')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
