# Generated by Django 5.0.8 on 2024-10-18 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_manage', '0005_deviceconfigblock'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviceConfigBlock',
        ),
    ]
