# Generated by Django 5.0.8 on 2024-10-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_manage', '0006_delete_deviceconfigblock'),
        ('dcim', '0187_alter_device_vc_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevicePollConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('poll_frequency', models.CharField(default='daily', max_length=10)),
                ('last_polled_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll_config', to='dcim.device')),
            ],
        ),
    ]
